### ISSUE TITLE
Support intel qsv?

### ISSUE THREAD

**Issue by juzi5201314** [Proryanator/encoder-benchmark#11]
Hi, I stumbled across this repo and it looks interesting, I have an intel arc graphics card and I'm very interested in its encoder performance tests. Are there plans to add support for qsv? or maybe I can submit a pr to try and support it (but wait until I'm free and spend a little time familiarizing yourself with your project)😉

**Comment by Proryanator** [comment]
Yes definitely. I'd like to pickup a cheap A380 to add in AV1 support. Stay tuned!

**Comment by Proryanator** [comment]
Intel Arc GPU is on it's way, stay tuned!

**Comment by Proryanator** [comment]
#14 PR added in support for AV1, and was released into [v0.6.1-alpha](https://github.com/Proryanator/encoder-benchmark/releases/tag/v0.6.0-alpha)!
