### ISSUE TITLE
Crash when launching the benchmark

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [Proryanator/encoder-benchmark#16]
i5-13500 with an Arc A770
Using the benchmark.exe, when asked if I want the verbose mode or not and answering, the cmd immediately closes, with no process happening in the background, and happens also when using the admin cmd as well

**Comment by Proryanator** [comment]
Thanks for opening the issue. Can you try opening a command prompt by hand and running it via ".\benchmark.exe"? That way the window won't close and we can see the error.

**Comment by TheWonderfulTartiflette** [comment]
Sorry for the late reply, but yes it works, only when opening it with the cmd and typing benchmark.exe

**Comment by Proryanator** [comment]
Hmm that's interesting, thanks for raising this. I'll make a note to look into what could be causing the crash.

**Comment by TheWonderfulTartiflette** [comment]
@Proryanator hey are there any updates on this?

**Comment by Proryanator** [comment]
@TheWonderfulTartiflette hey there! No updates yet but I can work on this ASAP!

**Comment by Proryanator** [comment]
@TheWonderfulTartiflette looking into this right now! May ping you if I have any questions.

**Comment by Proryanator** [comment]
The tools could definitely use some work around better error handling and propagating but, in the mean time I've added in a catch all for any unhandled error to at least keep the cmd prompt open.

Can you download this build and try again? Should be able to see the error that was thrown right before and help troubleshoot more.

[benchmark.zip](https://github.com/Proryanator/encoder-benchmark/files/12622986/benchmark.zip)

**Comment by Proryanator** [comment]
Going to go ahead and close this out as resolved. @TheWonderfulTartiflette do let me know if you still have issues and we can re-open this issue!
