### ISSUE TITLE
Can't get latest ffmpeg logs due to non existent CreationTime / Birth Time for files in Linux

### ISSUE THREAD

**Issue by e-dong** [Proryanator/encoder-benchmark#22]
jI am using an Artix based linux distro and I noticed the vmaf scores are all 0 in the log file when running the benchmark tool. The same occurs when running the permutor-cli tool without the `-c` flag.

## Setup
1. clone repo
2. cargo run --bin benchmark -r
3. cargo run --bin permutor-cli -r
4. copy binaries from target/release to PATH
5. copy source files into ssd `/usr/share/benchmark/encoding_files`
6. cd into dir above and ran `benchmark` / `permutor-cli`

### Installed Dependencies
ffmpeg/ffprobe 6.0 (https://archlinux.org/packages/extra/x86_64/ffmpeg/)

Also tried these AUR packages, but got same error
* https://aur.archlinux.org/packages/ffmpeg-git
* https://aur.archlinux.org/packages/ffmpeg-full-git

## Permutor CLI Stacktrace Info 
When providing the permutor-cli tool with the `-c` flag, it errors out.
command: `RUST_BACKTRACE=full permutor-cli -v -e h264_nvenc -s 4k-60.y4m -c -b 10 -m 100 -t`

output

```
...
  Average FPS:  49
  1%'ile:       42
  90%'ile:      46

Calculating vmaf score; might take longer than original encode depending on your CPU...
V: Vmaf args calculating quality: -y -report -r 60 -i tcp://localhost:2000?listen -r 60 -i 4k-60.y4m -filter_complex libvmaf='n_threads=12:n_subsample=5' -f null -
V: ffmpeg args: [-y -report -r 60 -i tcp://localhost:2000?listen -r 60 -i 4k-60.y4m -filter_complex libvmaf='n_threads=12:n_subsample=5' -f null -]
V: ffmpeg args no network calls (copy this and run locally, minus the quotes): [-y -report -r 60 -i tcp://localhost:2000?listen -r 60 -i 4k-60.y4m -filter_complex libvmaf='n_threads=12:n_subsample=5' -f null -]
V: Encoder fmmpeg args sending to vmaf: -progress tcp://localhost:1234 -stats_period 0.5 -y -i 4k-60.y4m -b:v 10M -c:v h264_nvenc -preset p1 -tune hq -profile:v high -rc cbr -cbr true -gpu 0 -f h264 tcp://localhost:2000
V: ffmpeg args: [-progress tcp://localhost:1234 -stats_period 0.5 -y -i 4k-60.y4m -b:v 10M -c:v h264_nvenc -preset p1 -tune hq -profile:v high -rc cbr -cbr true -gpu 0 -f h264 tcp://localhost:2000]
V: ffmpeg args no network calls (copy this and run locally, minus the quotes): [-y -i 4k-60.y4m -b:v 10M -c:v h264_nvenc -preset p1 -tune hq -profile:v high -rc cbr -cbr true -gpu 0 -f null -]
VMAF calculation finishing up...
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ffmpeg/src/report_files.rs:24:91
...
```
 [error.log](https://github.com/Proryanator/encoder-benchmark/files/12621834/error.log)

[ffmpeg-20230915-123232.log](https://github.com/Proryanator/encoder-benchmark/files/12621848/ffmpeg-20230915-123232.log)

**Comment by e-dong** [comment]
Hmm the docs say:
>pub fn [from_creation_time](https://docs.rs/filetime_creation/latest/filetime_creation/struct.FileTime.html#method.from_creation_time)(meta: &[Metadata](https://doc.rust-lang.org/nightly/std/fs/struct.Metadata.html)) -> [Option](https://doc.rust-lang.org/nightly/core/option/enum.Option.html)<[FileTime](https://docs.rs/filetime_creation/latest/filetime_creation/struct.FileTime.html)>
Creates a new timestamp from the creation time listed in the specified metadata.

>The returned value corresponds to the birthtime field of stat on Unix platforms and the ftCreationTime field on Windows platforms. Note that not all Unix platforms have this field available and may return None in some circumstances.

ref: https://docs.rs/filetime_creation/latest/filetime_creation/struct.FileTime.html#method.from_creation_time

I guess my Unix platform doesn't have this field, so it returns `None`

**Comment by Proryanator** [comment]
Hey there @e-dong! Thanks for opening this up, that's a weird issue I do see that in the [docs](https://docs.rs/filetime/latest/filetime/struct.FileTime.html#method.from_creation_time) as well 👀 

A quick test would be maybe swapping that out for `from_unix_time` and re-running on your linux distro. If that doesn't fix it quick though, we can keep this issue open and I can investigate a bit more to get it fixed for you.

**Comment by e-dong** [comment]
Interesting, I learned that some linux systems don't store the creation time. I wonder if I'm the first person trying this on linux lol.

I tried out this simple example from here and I can reproduce the error.
- https://github.com/alexcrichton/filetime/issues/74
- https://stackoverflow.com/questions/76946130/creation-time-is-not-available-on-this-platform-currently

I'm new to rust, so I ended up using last_modification_time so I could maintain the same "metadata" parameter
```
      while index != log_entries.len() {
          entry = log_entries.get(index);
          let file_time = FileTime::from_last_modification_time(&entry.unwrap().metadata().unwrap());
          if file_time > latest_time {
              latest_time = FileTime::from_last_modification_time(&entry.unwrap().metadata().unwrap());
              log_file = entry;
          }
...
```
Look like that is a workaround for now. 
```
[eric@m3tis /usr/share/benchmark/encoding_files]$ permutor-cli -e h264_nvenc -s 4k-60.y4m -c -t

Options:
  -calculating vmaf score
  -test run, will only run 1 permutation
[ETR: Unknown until first permutation is done]
[Permutation:   1/1]
[Resolution:    3840x2160]
[Encoder:       h264_nvenc]
[FPS:           60]
[Bitrate:       10Mb/s]
[-preset p1 -tune hq -profile:v high -rc cbr -cbr true -gpu 0]
  [00:00:38] [####################################################################################################################################################] 1800/1800 frames (00:00:00)
  Average FPS:  49
  1%'ile:       44
  90%'ile:      46

Calculating vmaf score; might take longer than original encode depending on your CPU...
  [00:01:28] [####################################################################################################################################################] 1800/1800 frames (00:00:00)
VMAF calculation finishing up...
VMAF score: 62.93657

Benchmark runtime: 2m28s

```

**Comment by Proryanator** [comment]
@e-dong hehe you might be the first end-user using it on Linux I think yeah! xD that score looks correct for 10Mb/s so that's a good sign.

I can test using `from_last_modification_time` on both Windows and Linux, and push up that as the fix if it works on both!

**Comment by e-dong** [comment]
No problem, I'm a big fan of the work you done putting all of this together! I will add a guide on the Sunshine docs using your awesome tools!

**Comment by e-dong** [comment]
@Proryanator aw spoke too soon I'm running into more errors. I will see how far I can get and report back to you.

**Comment by e-dong** [comment]
@Proryanator 
![Screenshot_20230915_224457_UserLAnd.jpg](https://github.com/Proryanator/encoder-benchmark/assets/16567905/aac9d764-466b-497a-9cdd-ede2c20c2381)

Ohh so I switched back to the official arch version of ffmpeg and it works now! I was getting  lower than normal fps values @4k (I have a RTX 3070) before with the AUR ffmpeg-full package.

The tcp connection was timing out or something so the command just hanged after trying to finish the cal of vmaf score. When I Ctrl +c I realize the error I got was because the script was reading 
`tcp @ 0x563aed8a2480] No default whitelist set` which doesn't match the regex to get the vmaf score lol.

**Comment by e-dong** [comment]
I made a PR with my fork, I also plan to add some Linux setup instructions in the readme.

**Comment by Proryanator** [comment]
Sweet thanks! Looks good, I'll probably build the tool and try it out on Windows, then I can get your PR in.

**Comment by e-dong** [comment]
>I was getting lower than normal fps values @4k (I have a RTX 3070)

Oops my sequential read speed is at like 525 MB/s lol.
![Screenshot_20230917_073559_UserLAnd.jpg](https://github.com/Proryanator/encoder-benchmark/assets/16567905/7f08edc3-19df-400f-88f4-91a4efb65250)

Learned you can do this easily in Linux
https://www.baeldung.com/linux/disk-performance-test

**Comment by Proryanator** [comment]
@e-dong PR is merged in! You mind if I close thise issue out? 👊
