### ISSUE TITLE
Add Linux build/test running support

### ISSUE THREAD

**Issue by Proryanator** [Proryanator/encoder-benchmark#26]
Let's add in support for building binaries for Linux x86_64, as well as add in pipeline jobs to run unit tests against at least 1 linux box.

This should help to catch future linux-only platform issues like the one mentioned in #22

**Comment by e-dong** [comment]
@Proryanator In the meantime, I suggest adding instructions in the readme about steps to setup rust environment and building an executable. I thought the minimum spec requirement was misleading haha, otherwise I would try these tools out sooner. This might be something I can add.

**Comment by e-dong** [comment]
I can work on adding an AUR package. I believe we have to start out as an AUR package before entering the Arch official repos. Alternatively we can have the workflow build the PKGBUILD binaries to allow users download it. This is only specific to Arch based distro tho.

We still need support for Debian, rhel/fedora. Perhaps we can copy why Sunshine supports lol
https://docs.lizardbyte.dev/projects/sunshine/en/nightly/about/installation.html#linux

**Comment by Proryanator** [comment]
Ye! I think supporting some of the major Linux distros with downloadable binaries would be the best in their various forms 👍

We could have separate issues for debian, arch, etc. (smaller issues make it easier to validate and isolate things).
