### ISSUE TITLE
Format entire project using rustfmt, update readme with how to run rustfmt and add in a job (in IDE's too)

### ISSUE THREAD

**Issue by Proryanator** [Proryanator/encoder-benchmark#33]
https://github.com/Proryanator/encoder-benchmark/pull/32

rustfmt was used in the above PR, which pointed out that we don't have a way to catch/prevent mis-formatted code from getting into the code base.

This should be relatively simple to setup via adding a new github action/job.

**To-Do:**
- add a new job that runs `rustfmt --check` via docs [here](https://github.com/rust-lang/rustfmt#verifying-code-is-formatted) that will run before any other jobs for your PR. Job should block the PR and suggest running rustfmt locally to fix the formatting issues
- format the entire project using rustfmt (to establish a clean repo)
- add section to the README's Contributing section to discuss how to run rustfmt (including various ways to automatically run this in your IDE)

**Comment by Proryanator** [comment]
![Screenshot 2023-09-27 at 11 20 31 AM](https://github.com/Proryanator/encoder-benchmark/assets/8595173/af3c4c79-6f11-4cc3-adea-a65fa11e8d23)

(how to do this in RustRover or other Jetbrains tools)

**Comment by e-dong** [comment]
This would be good to do! This will make sure the diff are cleaner in future PRs haha
