### ISSUE TITLE
Update constant download url listed in the project to match the readme

### ISSUE THREAD

**Issue by Proryanator** [Proryanator/encoder-benchmark#43]
A quick update to fix download issues for the original file hosting location was done to the readme, but not the constant stored in the project.

Let's make these the same. Ideally there would be a .prop file (or whatever the rust equivalent is) that both the readme and the project references, so we only need to update this once in the future.

**Comment by Proryanator** [comment]
There's not a clean way to reference a variable defined in a file in a readme; best we can do is reference a whole file, or setup a job that updates the README should the download URL changes.

However, I think we can store the download link in the readme, then pull that into the CLI (via readme parsing).

**Comment by e-dong** [comment]
@Proryanator This could be an option, but might be overkill lol
https://jekyllrb.com/docs/liquid/
