### ISSUE TITLE
Update release version in benchmark figlet title

### ISSUE THREAD

**Issue by e-dong** [Proryanator/encoder-benchmark#44]
The following needs to be updated to the latest version. I'm also wondering if permutor-cli should also ref the version when invoking the help flag.

Reference: https://github.com/Proryanator/encoder-benchmark/blob/main/benchmark/src/main.rs#L292

**Comment by Proryanator** [comment]
Ah yes, we ought to update the release job automatically to update this I think.

What people usually do is, leave the version set to "DEV" in the code but in the release jobs, replace that with the real version right before building.

So development locally will always show "DEV" but, the binaries will say the actual version.
